{{- if .Values.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-metrics.fullname" . }}
  labels:
    app: {{ template "gitlab-metrics.name" . }}
    chart: {{ template "gitlab-metrics.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  token: {{ .Values.token | b64enc | quote }}
{{- end -}}
